new_local_repository(
    name = "cuda",
    build_file = "tools/cuda.BUILD",
    path = "/usr/local/cuda/"
)

new_local_repository(
    name = "openscenegraph",
    build_file = "tools/openscenegraph.BUILD",
    path = "../OpenSceneGraph/build/local_install/"
)

new_local_repository(
    name = "qt4",
    path = "/usr/include/qt4",
    build_file = "tools/qt4.BUILD"
)

new_local_repository(
    name = "glib2",
    path = "/usr/",
    build_file = "tools/glib2.BUILD"
)

new_http_archive(
    name = "boost",
    build_file = "tools/boost.BUILD",
    sha256 = "5721818253e6a0989583192f96782c4a98eb6204965316df9f5ad75819225ca9",
    type = "tar.bz2",
    url = "https://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.tar.bz2",
)

new_http_archive(
    name = "eigen",
    build_file = "tools/eigen.BUILD",
    sha256 = "dd254beb0bafc695d0f62ae1a222ff85b52dbaa3a16f76e781dce22d0d20a4a6",
    type = "tar.bz2",
    url = "http://bitbucket.org/eigen/eigen/get/3.3.4.tar.bz2",
)
